# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Filip Gudjevski
title: Software Engineer | AWS Solutions Architect
email: filip.gudjevski@tuliptp.com
website: tuliptp.com

# Social links
# twitter_username: ivicamicev
github_username:  gudzo
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: gudzo
linkedin_username: filipgudjevski
# pinterest_username: jekyll
# youtube_username: ivica.micev
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  A versatile software engineer with 5+ years experience in creating RESTful web services and automation with a focus AWS standard and best practices. 

  I am most skilled in: <mark>AWS</mark>, <mark>JAVA</mark>,<mark>Automation</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Cloud Technologies, JAVA and automation of all kinds, some of my other interests and hobbies are:
   - Basketball
   - Snowboarding

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
